apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Default values for xl.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic

  # Global settings
  global:
  #  registry: index.docker.io
  #  imageUsername: turbouser
  #  imagePassword: turbopassword
    repository: turbonomic
    tag: 7.22.8
    #externalIP: 10.0.2.15
    #externalDbIP: 10.0.2.15
    #externalTimescaleDBIP: 10.0.2.15

# Component selector - Probes
#  actionscript:
#    enabled: true
#  appdynamics:
#    enabled: true
#  appinsights:
#    enabled: true
#  aws:
#    enabled: true
#  azure:
#    enabled: true
#  dynatrace:
#    enabled: true
#  hpe3par:
#    enabled: true
#  horizon:
#    enabled: false
#  hyperflex:
#    enabled: false
#  hyperv:
#    enabled: true
#  netapp:
#    enabled: true
#  nutanix:
#    enabled: true
#  oneview:
#    enabled: true
#  pure:
#    enabled: true
#  scaleio:
#    enabled: false
#  servicenow:
#    enabled: false
#  ucs:
#    enabled: true
#  udt:
#    enabled: true
#  vcenter:
#    enabled: true
#  vmax:
#    enabled: true
#  vmm:
#    enabled: true
#  wmi:
#    enabled: true
#  snmp:
#    enabled: true
#  mssql:
#    enabled: true
#  mysql:
#    enabled: false
#  newrelic:
#    enabled: true
#  tomcat:
#    enabled: false
