dependencies:
# Base dependencies
  - name: arangodb
    repository: file://../base/arangodb
    version: 0.1.0
    condition: control.enabled,platform.enabled
  - name: consul
    repository: file://../base/consul
    version: 0.1.0
    condition: platform.enabled
  - name: db
    repository: file://../base/db
    version: 0.1.0
    condition: platform.enabled
  - name: influxdb
    repository: file://../base/influxdb
    version: 0.1.0
    condition: metron.enabled
  - name: postgresql
    repository: file://../base/postgresql
    version: 6.3.2
    condition: timescaledb.enabled
  - name: kafka
    repository: file://../base/kafka
    version: 0.1.0
    condition: platform.enabled
  - name: nginx
    repository: file://../base/nginx
    version: 0.1.0
    condition: nginxingress.enabled
  - name: rsyslog
    repository: file://../base/rsyslog
    version: 0.1.0
  - name: zookeeper
    repository: file://../base/zookeeper
    version: 0.1.0
    condition: platform.enabled

# Services dependencies
  - name: api
    repository: file://../services/api
    version: 0.1.0
    condition: platform.enabled
  - name: auth
    repository: file://../services/auth
    version: 0.1.0
    condition: platform.enabled
  - name: action-orchestrator
    repository: file://../services/action-orchestrator
    version: 0.1.0
    condition: control.enabled,platform.enabled
  - name: clustermgr
    repository: file://../services/clustermgr
    version: 0.1.0
    condition: platform.enabled
  - name: cost
    repository: file://../services/cost
    version: 0.1.0
    condition: control.enabled,platform.enabled
  - name: group
    repository: file://../services/group
    version: 0.1.0
    condition: platform.enabled
  - name: history
    repository: file://../services/history
    version: 0.1.0
    condition: control.enabled,platform.enabled
  - name: market
    repository: file://../services/market
    version: 0.1.0
    condition: control.enabled,platform.enabled
  - name: ml-datastore
    repository: file://../services/ml-datastore
    version: 0.1.0
    condition: metron.enabled
  - name: ml-training
    repository: file://../services/ml-training
    version: 0.1.0
    condition: training.enabled
  - name: plan-orchestrator
    repository: file://../services/plan-orchestrator
    version: 0.1.0
    condition: control.enabled,platform.enabled
  - name: repository
    repository: file://../services/repository
    version: 0.1.0
    condition: platform.enabled
  - name: topology-processor
    repository: file://../services/topology-processor
    version: 0.1.0
    condition: platform.enabled
  - name: extractor
    repository: file://../services/extractor
    version: 0.1.0
    condition: extractor.enabled # todo: change to platform.enabled once XLR/search is ready

# Logging dependencies
  - name: elasticsearch
    repository: file://../base/elasticsearch
    version: 1.24.0
    condition: global.elk
  - name: kibana
    repository: file://../base/kibana
    version: 2.2.0
    condition: global.elk
  - name: logstash
    repository: file://../base/logstash
    version: 1.7.0
    condition: global.elk
  - name: loki
    repository: file://../base/loki
    version: "^0.20.0"
    condition: loki.enabled
  - name: promtail
    repository: file://../base/promtail
    version: "^0.15.0"
    condition: promtail.enabled
  - name: fluent-bit
    repository: file://../base/fluent-bit
    version: "^0.0.2"
    condition: fluent-bit.enabled

# Monitoring dependencies
  - name: prometheus
    repository: file://../base/prometheus
    version: 9.5.0
    condition: prometheus.enabled
  - name: prometheus-mysql-exporter
    repository: file://../base/prometheus-mysql-exporter
    version: 0.5.2
    condition: prometheus-mysql-exporter.enabled
  - name: grafana
    repository: file://../base/grafana
    version: 5.1.25
    condition: grafana.enabled,reporting.enabled
  - name: kubeturbo
    repository: file://../base/kubeturbo
    version: 0.1.0
    condition: kubeturbo.enabled
  - name: prometurbo
    repository: file://../base/prometurbo
    version: 0.1.0
    condition: prometurbo.enabled
  - name: chronograf
    repository: file://../base/chronograf
    version: 1.1.0
    condition: chronograf.enabled
  - name: datacloud
    repository: file://../base/datacloud
    version: 0.1.0
    condition: datacloud.enabled

# Tracing dependencies
  - name: jaeger
    repository: file://../base/jaeger
    version: 0.13.0
    condition: jaeger.enabled
  - name: cassandra
    version: ^0.13.1
    repository: file://../base/cassandra
    condition: jaeger.enabled, jaeger.provisionDataStore.cassandra
#  - name: elasticsearch
#    version: ^1.24.1
#    repository: file://../base/elasticsearch
#    condition: jaeger.enabled, jaeger.provisionDataStore.elasticsearch

# Integration dependencies
  - name: intersight-integration
    repository: file://../services/intersight-integration
    version: 0.1.0
    condition: intersight-integration.enabled

# Mediation dependencies
  - name: mediation-actionscript
    repository: file://../probes/mediation-actionscript
    version: 0.1.0
    condition: actionscript.enabled
  - name: mediation-aix
    repository: file://../probes/mediation-aix
    version: 0.1.0
    condition: aix.enabled
  - name: mediation-appdynamics
    repository: file://../probes/mediation-appdynamics
    version: 0.1.0
    condition: appdynamics.enabled
  - name: mediation-appinsights
    repository: file://../probes/mediation-appinsights
    version: 0.1.0
    condition: appinsights.enabled
  - name: mediation-aws
    repository: file://../probes/mediation-aws
    version: 0.1.0
    condition: aws.enabled
  - name: mediation-awsbilling
    repository: file://../probes/mediation-awsbilling
    version: 0.1.0
    condition: aws.enabled
  - name: mediation-awscost
    repository: file://../probes/mediation-awscost
    version: 0.1.0
    condition: aws.enabled
  - name: mediation-baremetal
    repository: file://../probes/mediation-baremetal
    version: 0.1.0
    condition: baremetal.enabled
  - name: mediation-datadog
    repository: file://../probes/mediation-datadog
    version: 0.1.0
    condition: datadog.enabled
  - name: mediation-awslambda
    repository: file://../probes/mediation-awslambda
    version: 0.1.0
    condition: awslambda.enabled
  - name: mediation-azure
    repository: file://../probes/mediation-azure
    version: 0.1.0
    condition: azure.enabled
  - name: mediation-azurecost
    repository: file://../probes/mediation-azurecost
    version: 0.1.0
    condition: azure.enabled
  - name: mediation-azureea
    repository: file://../probes/mediation-azureea
    version: 0.1.0
    condition: azure.enabled
  - name: mediation-azuresp
    repository: file://../probes/mediation-azuresp
    version: 0.1.0
    condition: azure.enabled
  - name: mediation-azurevolumes
    repository: file://../probes/mediation-azurevolumes
    version: 0.1.0
    condition: azure.enabled
  - name: mediation-cloudfoundry
    repository: file://../probes/mediation-cloudfoundry
    version: 0.1.0
    condition: cloudfoundry.enabled
  - name: mediation-compellent
    repository: file://../probes/mediation-compellent
    version: 0.1.0
    condition: compellent.enabled
  - name: mediation-customdata
    repository: file://../probes/mediation-customdata
    version: 0.1.0
    condition: customdata.enabled
  - name: mediation-dynatrace
    repository: file://../probes/mediation-dynatrace
    version: 0.1.0
    condition: dynatrace.enabled
  - name: mediation-gcp
    repository: file://../probes/mediation-gcp
    version: 0.1.0
    condition: gcp.enabled
  - name: mediation-gcpcost
    repository: file://../probes/mediation-gcpcost
    version: 0.1.0
    condition: gcp.enabled
  - name: mediation-hds
    repository: file://../probes/mediation-hds
    version: 0.1.0
    condition: hds.enabled
  - name: mediation-hpe3par
    repository: file://../probes/mediation-hpe3par
    version: 0.1.0
    condition: hpe3par.enabled
  - name: mediation-horizon
    repository: file://../probes/mediation-horizon
    version: 0.1.0
    condition: horizon.enabled
  - name: mediation-hyperflex
    repository: file://../probes/mediation-hyperflex
    version: 0.1.0
    condition: hyperflex.enabled
  - name: mediation-hyperv
    repository: file://../probes/mediation-hyperv
    version: 0.1.0
    condition: hyperv.enabled
  - name: mediation-intersight
    repository: file://../probes/mediation-intersight
    version: 0.1.0
    condition: intersight.enabled
  - name: mediation-intersighthyperflex
    repository: file://../probes/mediation-intersighthyperflex
    version: 0.1.0
    condition: intersight.enabled
  - name: mediation-intersightucs
    repository: file://../probes/mediation-intersightucs
    version: 0.1.0
    condition: intersight.enabled
  - name: mediation-istio
    repository: file://../probes/mediation-istio
    version: 0.1.0
    condition: istio.enabled
  - name: mediation-netapp
    repository: file://../probes/mediation-netapp
    version: 0.1.0
    condition: netapp.enabled
  - name: mediation-netflow
    repository: file://../probes/mediation-netflow
    version: 0.1.0
    condition: netflow.enabled
  - name: mediation-newrelic
    repository: file://../probes/mediation-newrelic
    version: 0.1.0
    condition: newrelic.enabled
  - name: mediation-nutanix
    repository: file://../probes/mediation-nutanix
    version: 0.1.0
    condition: nutanix.enabled
  - name: mediation-mssql
    repository: file://../probes/mediation-mssql
    version: 0.1.0
    condition: mssql.enabled
  - name: mediation-oneview
    repository: file://../probes/mediation-oneview
    version: 0.1.0
    condition: oneview.enabled
  - name: mediation-openstack
    repository: file://../probes/mediation-openstack
    version: 0.1.0
    condition: openstack.enabled
  - name: mediation-pivotal
    repository: file://../probes/mediation-pivotal
    version: 0.1.0
    condition: pivotal.enabled
  - name: mediation-pure
    repository: file://../probes/mediation-pure
    version: 0.1.0
    condition: pure.enabled
  - name: mediation-rhv
    repository: file://../probes/mediation-rhv
    version: 0.1.0
    condition: rhv.enabled
  - name: mediation-scaleio
    repository: file://../probes/mediation-scaleio
    version: 0.1.0
    condition: scaleio.enabled
  - name: mediation-servicenow
    repository: file://../probes/mediation-servicenow
    version: 0.1.0
    condition: servicenow.enabled
  - name: mediation-snmp
    repository: file://../probes/mediation-snmp
    version: 0.1.0
    condition: snmp.enabled
  - name: mediation-terraform
    repository: file://../probes/mediation-terraform
    version: 0.1.0
    condition: terraform.enabled
  - name: mediation-tetration
    repository: file://../probes/mediation-tetration
    version: 0.1.0
    condition: tetration.enabled
  - name: mediation-ucs
    repository: file://../probes/mediation-ucs
    version: 0.1.0
    condition: ucs.enabled
  - name: mediation-ucsdirector
    repository: file://../probes/mediation-ucsdirector
    version: 0.1.0
    condition: ucsdirector.enabled
  - name: mediation-vcenter
    repository: file://../probes/mediation-vcenter
    version: 0.1.0
    condition: vcenter.enabled
  - name: mediation-vcenterbrowsing
    repository: file://../probes/mediation-vcenterbrowsing
    version: 0.1.0
    condition: vcenter.enabled
  - name: mediation-vcd
    repository: file://../probes/mediation-vcd
    version: 0.1.0
    condition: vcd.enabled
  - name: mediation-vmax
    repository: file://../probes/mediation-vmax
    version: 0.1.0
    condition: vmax.enabled
  - name: mediation-vmm
    repository: file://../probes/mediation-vmm
    version: 0.1.0
    condition: vmm.enabled
  - name: mediation-vplex
    repository: file://../probes/mediation-vplex
    version: 0.1.0
    condition: vplex.enabled
  - name: mediation-wmi
    repository: file://../probes/mediation-wmi
    version: 0.1.0
    condition: wmi.enabled
  - name: mediation-xtremio
    repository: file://../probes/mediation-xtremio
    version: 0.1.0
    condition: xtremio.enabled
