apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
  labels:
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: arangodb-apps
  name: {{ .Chart.Name }}-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-dump
  labels:
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}-dump
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: secure
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{ toYaml .Values.env | indent 8 -}}
        readinessProbe:
          httpGet:
            port: 8529
            path: /_admin/server/availability
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/arangodb3
          name: arangodb
        - mountPath: /var/lib/arangodb3-apps
          name: arangodb-apps
        - mountPath: /home/arangodb/arangodb-dump
          name: arangodb-dump
        - mountPath: /tmp
          name: arangodb-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 1800
      volumes:
      - name: arangodb
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}
      - name: arangodb-apps
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-apps
      - name: arangodb-dump
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-dump
      - name: arangodb-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: tcp-arangodb
    port: 8529
  - name: http-arangodb-dump
    port: 8599
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
